### ISSUE TITLE
Where to Put SketchyBar Module

### ISSUE THREAD

**Issue by jrock2004** [john-json/dotfiles#2]
When I try to start it says: module 'sketchybar' not found. I notice you have a module but not sure where to put it

**Comment by john-json** [comment]
are you using sketchybar with lua?

**Comment by jrock2004** [comment]
Yes. I decided to just follow how to setup Sketchybar for my self and learn a little first

**Comment by jrock2004** [comment]
Oh so I think I missed setting up LUA support and thought it was baked in https://github.com/FelixKratz/SbarLua
